### ISSUE TITLE
Making core optional causing no module names absl error

### ISSUE THREAD

**Issue by samos123** [apple/axlearn#628]
Launching a tpu job on GKE threw this error in the container:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/axlearn/common/launch_trainer_main.py", line 5, in <module>
    from absl import app, flags
ModuleNotFoundError: No module named 'absl'
```

I believe this is due to this commit which made the core depencies optional: https://github.com/apple/axlearn/commit/eb7d655758d874ae9a9ded4701ec99f669e0bb04

This is how I launch my GKE TPU job:
```
axlearn gcp gke start --instance_type=tpu-v5litepod-256 --num_replicas=1 \
        --cluster=snip-us-west4 \
        --queue=multislice-queue \
        --bundler_spec=allow_dirty=True \
        --bundler_type=artifactregistry --bundler_spec=image=tpu \
        --bundler_spec=dockerfile=Dockerfile --bundler_spec=target=tpu \
        -- python3 -m axlearn.common.launch_trainer_main \
        --module=text.gpt.c4_trainer --config=fuji-7B-v2 \
          --trainer_dir=gs://snip-multipod-axlearn \
          --data_dir=gs://axlearn-public/tensorflow_datasets  \
          --jax_backend=tpu
```

one fix that @jesus-orozco came up with is to use:
```
tpu = [
    "axlearn[core,gcp]",
    "jax[tpu]==0.4.28",  # must be >=0.4.19 for compat with v5p.
]
```

**Comment by markblee** [comment]
Should be addressed by #629.
